class AytSubjectsData {
  List<String> mathSubjects = [
    "",
    "Temel Kavramlar",
    "Rasyonel Sayılar",
    "EBOB – EKOK",
    "Oran – Orantı",
    "Mantık",
    "Kümeler",
    "Bölünebilme Kuralları",
    "1. Dereceden Denklem ve Eşitsizlikler",
    "Üslü İfadeler",
    "Üçgenler",
    "Veri – Seçme ve Sıralama",
    "Fonksiyonlar",
    "Polinomlar",
    "Parabol",
    "İkinci Dereceden Denklemler",
    "Çokgenler",
    "Katı Cisimler",
    "Trigonometrik Fonksiyonlar",
    "Doğrunun Analitik İncelenmesi",
    "İkinci Dereceden Fonksiyonlar ve Grafikleri",
    "Çember – Daire",
    "Permütasyon – Kombinasyon – Olasılık",
    "Üstel Fonksiyonlar – Logaritmik Fonksiyonlar",
    "Diziler",
    "Trigonometri",
    "Limit – Süreklilik",
    "Türev",
    "Belirsiz İntegral",
    "Belirli İntegral",
    "Çemberin Analitik İncelenmesi"
  ];

  List<String> geometrySubjects = [
    "",
    "Açılar ve Üçgenler",
    "Doğruda ve Üçgende Açılar",
    "Dik Üçgen",
    "Özel Üçgen",
    "İkizkenar ve Eşkenar Üçgen",
    "Açı Kenar Bağıntıları",
    "Üçgende Eşlik ve Benzerlik",
    "Üçgende Açıortay",
    "Üçgende Kenarortay",
    "Üçgende Alan",
    "Çokgenler",
    "Dörtgenler",
    "Yamuk",
    "Paralelkenar",
    "Eşkenar Dörtgen",
    "Deldoid",
    "Dikdörtgen",
    "Kare",
    "Çember ve Daire",
    "Doğrunun Analitik İncelenmesi",
    "Katı Cisimler",
    "Dikdörtgenler Prizması",
    "Küp",
    "Silindir",
    "Piramit",
    "Koni",
    "Küre"
  ];

  List<String> historySubjects = [
    "",
    "Tarih ve Zaman",
    "İnsanlığın İlk Dönemleri",
    "Ortaçağ’da Dünya",
    "İlk ve Orta Çağlarda Türk Dünyası",
    "İslam Medeniyetinin Doğuşu",
    "İlk Türk İslam Devletleri",
    "Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi",
    "Beylikten Devlete Osmanlı Siyaseti(1300-1453)",
    "Dünya Gücü Osmanlı Devleti (1453-1600)",
    "Yeni Çağ Avrupa Tarihi",
    "Yakın Çağ Avrupa Tarihi",
    "Osmanlı Devletinde Arayış Yılları",
    "18. Yüzyılda Değişim ve Diplomasi",
    "En Uzun Yüzyıl",
    "Osmanlı Kültür ve Medeniyeti",
    "20. Yüzyılda Osmanlı Devleti",
    "I. Dünya Savaşı",
    "Mondros Ateşkesi, İşgaller ve Cemiyetler",
    "Kurtuluş Savaşına Hazırlık Dönemi",
    "I. TBMM Dönemi",
    "Kurtuluş Savaşı ve Antlaşmalar",
    "II. TBMM Dönemi ve Çok Partili Hayata Geçiş",
    "Türk İnkılabı",
    "Atatürk İlkeleri",
    "Atatürk Dönemi Türk Dış Politikası"
  ];
  List<String> geographySubjects = [
    "",
    "Doğa ve İnsan",
    "Dünya’nın Şekli ve Hareketleri",
    "Coğrafi Konum",
    "Harita Bilgisi",
    "Atmosfer ve Sıcaklık",
    "İklimler",
    "Basınç ve Rüzgarlar",
    "Nem, Yağış ve Buharlaşma",
    "İç Kuvvetler / Dış Kuvvetler",
    "Su – Toprak ve Bitkiler",
    "Nüfus",
    "Göç",
    "Yerleşme",
    "Türkiye’nin Yer Şekilleri",
    "Ekonomik Faaliyetler",
    "Bölgeler",
    "Uluslararası Ulaşım Hatları",
    "Çevre ve Toplum",
    "Doğal Afetler"
  ];
  List<String> philosophySubjects = [
    "",
    "Felsefeye Giriş",
    "Bilgi Felsefesi",
    "Varlık Felsefesi",
    "Ahlak Felsefesi",
    "Sanat Felsefesi",
    "Din Felsefesi",
    "Siyaset Felsefesi",
    "Bilim Felsefesi"
  ];

  List<String> physicsSubjects = [
    "",
    "Fizik Bilimine Giriş",
    "Madde ve Özellikleri",
    "Kuvvet ve Hareket",
    "İş – Güç – Enerji",
    "Isı – Sıcaklık – Genleşme",
    "Elektrostatik",
    "Elektrik ve Manyetizma",
    "Basınç – Kaldırma Kuvveti",
    "Dalgalar",
    "Optik",
    "Kütle Merkezi – Tork – Denge",
    "Atışlar",
    "Basit Makineler",
    "Düzgün Çembersel Hareket",
    "Basit Harmonik Hareket",
    "Atom Fiziğine Giriş ve Radyoaktivite",
    "Modern Fizik"
  ];

  List<String> chemistrySubjects = [
    "",
    "Kimya Bilimi",
    "Atom ve Periyodik Sistem",
    "Modern Atom Teorisi",
    "Kimyasal Türler Arası Tepkimeler",
    "Kimyasal Hesaplamalar",
    "Asit, Baz ve Tuz",
    "Maddenin Halleri",
    "Gazlar",
    "Karışımlar",
    "Sıvı Çözeltiler",
    "Kimya ve Enerji",
    "Tepkimelerde Hız ve Denge",
    "Kimya ve Elektrik",
    "Karbon Kimyasına Giriş",
    "Endüstride ve Canlılarda Enerji",
    "Kimya Her Yerde"
  ];

  List<String> bioSubjects = [
    "",
    "Sinir Sistemi",
    "Endokrin Sistem",
    "Duyu Organları",
    "Destek ve Hareket Sistemi",
    "Sindirim Sistemi",
    "Dolaşım ve Bağışıklık Sistemi",
    "Solunum Sistemi",
    "Boşaltım Sistemi",
    "Üreme Sistemi ve Embriyonik Gelişim",
    "Komünite ve Popülasyon Ekolojisi",
    "Genetik Şifre-Protein Sentezi",
    "Fotosentez – Kemosentez",
    "Hücresel Solunum",
    "Bitki Biyolojisi",
    "Canlılar ve Çevre"
  ];

  List<String> literatureSubjects = [
    "",
    "Güzel Sanatlar ve Edebiyat",
    "Coşku ve Heyecan Dile Getiren Metinler",
    "Olay Çevresinde Oluşan Edebi Metinler",
    "Öğretici Metinler",
    "Tarih İçinde Türk Edebiyatı",
    "Destan Dönemi Türk Edebiyatı",
    "İslam Uygarlığı Çevresinde Gelişen Türk Edebiyatı",
    "Batı Tesirindeki Türk Edebiyatına Giriş",
    "Tanzimat Dönemi Edebiyatı",
    "Servet-i Fünun Edebiyatı",
    "Milli Edebiyat Dönemi",
    "Cumhuriyet Dönemi Türk Edebiyatı",
    "Cumhuriyet Döneminde Öğretici Metinler",
    "Cumhuriyet Döneminde Coşku ve Heyecanı Dile Getiren Metinler",
    "Cumhuriyet Döneminde Olay Çevresinde Oluşan Edebi Metinler"
  ];
}
