name: flutter_deneme_takip
description: "For kpss exam falseCount tracker"

linter:
  rules:
    avoid_print: false

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  sqflite: ^2.3.0

  provider: ^6.1.1

  fluttericon: ^2.0.0

  flutter_secure_storage: ^9.0.0

  font_awesome_flutter: ^10.6.0

  intl: ^0.18.1

  sqflite_common_ffi_web: ^0.4.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bg/
    - assets/img/
    - assets/img/icon/
    - assets/img/table_columns/
    - assets/img/table_columns/hs/
    - assets/img/table_columns/vt/
    - assets/img/table_columns/cg/
    - assets/img/table_columns/tr/
    - assets/img/table_columns/mt/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
