name: flutter_deneme_takip
description: "For kpss exam falseCount tracker"

linter:
  rules:
    avoid_print: false

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Local Database
  sqflite: ^2.3.0
  path: ^1.8.3

  #State Management
  provider: ^6.1.1

  #İcons and Fonts
  fluttericon: ^2.0.0
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0

  #Local Storage
  flutter_secure_storage: ^9.0.0

  #Date library
  intl: ^0.19.0

  #Loading effect
  shimmer: ^3.0.0

  #google login
  google_sign_in: ^6.2.1

  #firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

  google_api_availability: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/bg/
    - assets/img/
    - assets/img/icon/
    - assets/img/table_columns/
    - assets/img/table_columns/hs/
    - assets/img/table_columns/vt/
    - assets/img/table_columns/cg/
    - assets/img/table_columns/tr/
    - assets/img/table_columns/mt/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
